### ISSUE TITLE
App "Solid" cannot be installed because it is not compatible with this version of the server. configured

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/solid-nextcloud#125]
```
Nextcloud was successfully installed
  - installed: true
  - version: 27.0.0.8
  - versionstring: 27.0.0
  - edition: 
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false
App "Solid" cannot be installed because it is not compatible with this version of the server.
configured
```
